добавил сайт со списком рецептов
Rebace/KitchenBook pull request #3
Opened 2022-05-24 13:10 UTC by Rebace

2022-05-26 17:01 UTC, ReactiveTurtle requested changes

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Api.MessageContracts/RecipeModel/RecipeDto.cs
> +        public int Id { get; private set; }
Здесь везде просто set
Dto не является чем-то неизменяемым, он нужен только для передачи информации и конструктор по сути тогда будет не нужен
Отличие от доменных классов в том, что доменные объекты запоминает Entity Framework и следит за ними, с Dto такого нет, они приходят и уходят

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Api/ApiMessages/RecipeModel/RecipeMapper.cs
> +            return new Recipe
Думаю не надо так делать, будем создавать объект в методах Api, Dto не должен маппиться в доменный объект, так как маппинг предполагает преобразование, но для доменных объектом оно не нужно, мы можем достать их из базы или создать сами

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Api/ApiMessages/RecipeModel/RecipeMapper.cs
> +            return new RecipeDto
Соответственно здесь будет создаваться не через конструктор, а через фигурные скобки, присваивая полям значения

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Api/Controllers/RecipeController.cs
> +}
В конце нужна пустая строка, github просит)

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Domain/RecipeModel/IRecipeRepository.cs
> +        /*Task<Recipe>*/Recipe GetById(int id);
Давай сделаем асинхронными все методы используя Task<>, async, await

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Data/RecipeModel/Configuration/RecipeConfiguration.cs
> +            builder.Property(x => x.CookingTime).HasColumnType("byte");
Не маловато?)
Обычно над HasColumnType не заморачиваются

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Data/RecipeModel/Configuration/RecipeConfiguration.cs
> +            builder.Property(x => x.CookingTime).HasColumnType("byte");
Тем более ты в таблице указал int, а не byte

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Data/RecipeModel/Configuration/RecipeConfiguration.cs
> +            builder.Property(x => x.Description).HasMaxLength(255).IsRequired();
Не слишком мало для описания?
Думаю нужно убрать ограничение по длине для Description

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Data/RecipeModel/Configuration/RecipeConfiguration.cs
> +            builder.HasKey(x => x.Id);
Нужно добавить автогенерацию
            .Property(f => f.Id)
            .ValueGeneratedOnAdd();

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        {
Task, async, await

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Site/ClientApp/src/app/app.component.spec.ts
> +  it('should create the app', () => {
Думаю тесты можно удалить, я про файл)

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Site/ClientApp/src/app/app.component.ts
> +  title = 'ClientApp';
Почему здесь Title? Можно указать его в index.html

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Site/ClientApp/src/app/recipe-list/recipe-list-page/recipe-list-page.component.scss
> +            div{
Отступы, добавь их, если есть сомнения с тем как ставить отступы, то давай обговорим

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Site/ClientApp/src/app/recipe-list/recipe-list-routing.module.ts
> +
Лишняя пустая строка

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Site/ClientApp/src/app/recipe-list/recipe.service.ts
> +    public GetAll(): Observable<Recipe[]> {
названия методов, полей и переменных пишем с маленькой буквы, названия классов - с больших

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Site/ClientApp/src/app/recipe-list/shared/recipe.component/recipe.component.ts
> +  @Input() recipe: Recipe;
Давай-ка не будем игнорировать и поставим модификатор доступа public

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Site/ClientApp/src/app/recipe-list/shared/recipe.component/recipe.component.ts
> +    console.log(this.recipe.title);
Убрать console.log

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Site/ClientApp/src/index.html
> +    <title>ClientApp</title>
Поменяй title)

2022-05-26 17:01 UTC, ReactiveTurtle commented on src/KitchenBook.Site/ClientApp/src/styles.scss
> +$my-primary: mat.define-palette(mat.$indigo-palette, 100);
Либо добавь тему, либо убери)

2022-05-29 14:12 UTC, Rebace commented on src/KitchenBook.Api.MessageContracts/RecipeModel/RecipeDto.cs
> +        public int Id { get; private set; }
https://github.com/Rebace/KitchenBook/pull/3/commits/1a97c94f3db58b40c89612ecb16793b3b8759469#diff-cc094663cdab2b3dfa5733a6e4c04835d1c8adcbe46073c249670ffa2f5eb2caR12

2022-05-29 14:13 UTC, Rebace commented on src/KitchenBook.Api/ApiMessages/RecipeModel/RecipeMapper.cs
> +            return new Recipe
https://github.com/Rebace/KitchenBook/pull/3/commits/1a97c94f3db58b40c89612ecb16793b3b8759469#diff-7576f8c61610626247b9720ef12522391ffc44d1a58f25f3366d2739d25fbad9R15

2022-05-29 14:13 UTC, Rebace commented on src/KitchenBook.Api/ApiMessages/RecipeModel/RecipeMapper.cs
> +            return new RecipeDto
https://github.com/Rebace/KitchenBook/pull/3/commits/1a97c94f3db58b40c89612ecb16793b3b8759469#diff-7576f8c61610626247b9720ef12522391ffc44d1a58f25f3366d2739d25fbad9R15

2022-05-29 14:14 UTC, Rebace commented on src/KitchenBook.Api/ApiMessages/RecipeModel/RecipeMapper.cs
> +            return new Recipe
https://github.com/Rebace/KitchenBook/pull/3/commits/1a97c94f3db58b40c89612ecb16793b3b8759469#diff-7576f8c61610626247b9720ef12522391ffc44d1a58f25f3366d2739d25fbad9L13
https://github.com/Rebace/KitchenBook/pull/3/commits/1a97c94f3db58b40c89612ecb16793b3b8759469#diff-5e8f27d929f007b16607451622b95f2fd0b172b0cbbb4a564be6806b0e88a481R50

2022-05-29 14:17 UTC, Rebace commented on src/KitchenBook.Domain/RecipeModel/IRecipeRepository.cs
> +        /*Task<Recipe>*/Recipe GetById(int id);
[src/KitchenBook.Domain/RecipeModel/IRecipeRepository.cs](https://github.com/Rebace/KitchenBook/pull/3/commits/c96f9d3baf02613d89b264bdd9f435bfd1bd7569#diff-edf25509675ebff4a42a02e5ad79a13a81c265a99514a9d0aa42c29c08ad2c88)
https://github.com/Rebace/KitchenBook/pull/3/commits/c96f9d3baf02613d89b264bdd9f435bfd1bd7569#diff-0677a5b444726e7b7e707545170230a069ff8b66f6aed276a2f61c91819717be

2022-05-29 14:17 UTC, Rebace commented on src/KitchenBook.Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +        {
[src/KitchenBook.Infrastructure/Data/RecipeModel/RecipeRepository.cs](https://github.com/Rebace/KitchenBook/pull/3/commits/c96f9d3baf02613d89b264bdd9f435bfd1bd7569#diff-0677a5b444726e7b7e707545170230a069ff8b66f6aed276a2f61c91819717be)
https://github.com/Rebace/KitchenBook/pull/3/commits/c96f9d3baf02613d89b264bdd9f435bfd1bd7569#diff-5e8f27d929f007b16607451622b95f2fd0b172b0cbbb4a564be6806b0e88a481

2022-05-29 14:18 UTC, Rebace commented on src/KitchenBook.Infrastructure/Data/RecipeModel/Configuration/RecipeConfiguration.cs
> +            builder.Property(x => x.CookingTime).HasColumnType("byte");
https://github.com/Rebace/KitchenBook/pull/3/commits/c96f9d3baf02613d89b264bdd9f435bfd1bd7569#diff-0b07070f62ae50e6b08f68909739ee1044ab0864e90f4245ea66888f5f825ca6R14
https://github.com/Rebace/KitchenBook/pull/3/commits/c96f9d3baf02613d89b264bdd9f435bfd1bd7569#diff-0b07070f62ae50e6b08f68909739ee1044ab0864e90f4245ea66888f5f825ca6R14

2022-05-29 14:18 UTC, Rebace commented on src/KitchenBook.Infrastructure/Data/RecipeModel/Configuration/RecipeConfiguration.cs
> +            builder.Property(x => x.Description).HasMaxLength(255).IsRequired();
https://github.com/Rebace/KitchenBook/pull/3/commits/c96f9d3baf02613d89b264bdd9f435bfd1bd7569#diff-0b07070f62ae50e6b08f68909739ee1044ab0864e90f4245ea66888f5f825ca6R13

2022-05-29 14:19 UTC, Rebace commented on src/KitchenBook.Infrastructure/Data/RecipeModel/Configuration/RecipeConfiguration.cs
> +            builder.HasKey(x => x.Id);
https://github.com/Rebace/KitchenBook/pull/3/commits/c96f9d3baf02613d89b264bdd9f435bfd1bd7569#diff-0b07070f62ae50e6b08f68909739ee1044ab0864e90f4245ea66888f5f825ca6R11

2022-05-29 14:20 UTC, Rebace commented on src/KitchenBook.Site/ClientApp/src/app/app.component.spec.ts
> +  it('should create the app', () => {
https://github.com/Rebace/KitchenBook/pull/3/commits/bd27a996b3c3dbaf90651b254e36f15f827367ae#diff-ded974a6d533f77fd38f21c1089724c09f54f0d1b61af4a8e99cf2dc3c2042a3

2022-05-29 14:20 UTC, Rebace commented on src/KitchenBook.Site/ClientApp/src/app/app.component.ts
> +  title = 'ClientApp';
https://github.com/Rebace/KitchenBook/pull/3/commits/bd27a996b3c3dbaf90651b254e36f15f827367ae#diff-afe529b99b7743657dea44587ae2de7819d5991bbbdcae964c501c0ecb5bd587L9

2022-05-29 14:24 UTC, Rebace commented on src/KitchenBook.Site/ClientApp/src/app/recipe-list/recipe-list-routing.module.ts
> +
https://github.com/Rebace/KitchenBook/pull/3/commits/bd27a996b3c3dbaf90651b254e36f15f827367ae#diff-9dbf323aed749eb97a8237796a4f3435bad80b9babd7f73008174faf3ac03a8fL18

2022-05-29 14:25 UTC, Rebace commented on src/KitchenBook.Site/ClientApp/src/app/recipe-list/recipe.service.ts
> +    public GetAll(): Observable<Recipe[]> {
https://github.com/Rebace/KitchenBook/pull/3/commits/bd27a996b3c3dbaf90651b254e36f15f827367ae#diff-8fee4de46a22fe2c9d4f50dd377c6289ce93e328c0f81864eef7bde9fad764bbR13

2022-05-29 14:25 UTC, Rebace commented on src/KitchenBook.Site/ClientApp/src/app/recipe-list/shared/recipe.component/recipe.component.ts
> +  @Input() recipe: Recipe;
https://github.com/Rebace/KitchenBook/pull/3/commits/bd27a996b3c3dbaf90651b254e36f15f827367ae#diff-b11bcb20122d4c96c39604db00fcc9cfcbbe88623c0eaea245edd2fd5ec099b5R11

2022-05-29 14:25 UTC, Rebace commented on src/KitchenBook.Site/ClientApp/src/index.html
> +    <title>ClientApp</title>
https://github.com/Rebace/KitchenBook/pull/3/commits/bd27a996b3c3dbaf90651b254e36f15f827367ae#diff-b0aefc034d5a25d6f8a52f86e47674df7b3738bc54ed76910b91aa9f6558ce30R5

2022-05-29 14:26 UTC, Rebace commented on src/KitchenBook.Site/ClientApp/src/styles.scss
> +$my-primary: mat.define-palette(mat.$indigo-palette, 100);
https://github.com/Rebace/KitchenBook/pull/3/commits/1a97c94f3db58b40c89612ecb16793b3b8759469#diff-301540ade0e3f344660feb91b863273e1a669dd0a127f2020fd20f7fa9a77ff8L3

2022-05-29 14:26 UTC, Rebace commented on src/KitchenBook.Site/ClientApp/src/app/recipe-list/shared/recipe.component/recipe.component.ts
> +    console.log(this.recipe.title);
https://github.com/Rebace/KitchenBook/pull/3/commits/c96f9d3baf02613d89b264bdd9f435bfd1bd7569#diff-b11bcb20122d4c96c39604db00fcc9cfcbbe88623c0eaea245edd2fd5ec099b5L15

2022-05-29 15:32 UTC, Rebace commented on src/KitchenBook.Site/ClientApp/src/app/recipe-list/recipe-list-page/recipe-list-page.component.scss
> +            div{
https://github.com/Rebace/KitchenBook/pull/3/commits/b6529092fbd74d5d0e0c5bbc161020ae0068c3a2

2022-05-30 09:23 UTC, ReactiveTurtle approved these changes

2022-05-30 10:18 UTC, merged