добавил бэк для аутентификации
Rebace/KitchenBook pull request #4
Opened 2022-06-06 16:47 UTC by Rebace

2022-06-12 11:11 UTC, ReactiveTurtle commented
Сделай название PR более чётким, например: Добавил бэкенд для аутентификации пользователя
И коммиты делай тоже однообразно, я вижу. что иногда ты пишешь с маленькой буквы, а иногда с большой
Предлагаю начинать название с большой букве, по правилам русского языка)

2022-06-12 22:05 UTC, ReactiveTurtle requested changes

2022-06-12 22:05 UTC, ReactiveTurtle commented on src/KitchenBook.Api.MessageContracts/AuthenticateModel/AuthenticateDto.cs
> +    [Required]
Что за атрибут?

2022-06-12 22:05 UTC, ReactiveTurtle commented on src/KitchenBook.Api/Controllers/RecipeController.cs
>              var createdRecipe = await _recipeRepository.Create(new Recipe(recipeDto.Title, recipeDto.Description,
Каждый аргумент на свою строчку

2022-06-12 22:05 UTC, ReactiveTurtle commented on src/KitchenBook.Api/Controllers/UserController.cs
> +        if (Hashing.ToSHA256(loiginDto.Password) != user.Password)
Hashing.ToSHA256(loiginDto.Password) лучше вынести в переменную
Будет более наглядно

2022-06-12 22:05 UTC, ReactiveTurtle commented on src/KitchenBook.Api/Controllers/UserController.cs
> +        HttpContext.Response.Cookies.Append("Token", token);
Думаю можно создать Extension для Cookie

2022-06-12 22:05 UTC, ReactiveTurtle commented on src/KitchenBook.Domain/UserModel/IUserRepository.cs
> +
Убери пустую строку

2022-06-12 22:05 UTC, ReactiveTurtle commented on src/KitchenBook.Domain/UserModel/IUserRepository.cs
> +}
В конце файла нужна пустая строка, нужно для github

2022-06-12 22:05 UTC, ReactiveTurtle commented on src/KitchenBook.Domain/UserModel/User.cs
> +    public string? Description { get; private set; }
Напомни почему Description Nullable?

2022-06-12 22:05 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Data/RecipeModel/Configuration/RecipeConfiguration.cs
> -            builder.Property(x => x.Id).ValueGeneratedOnAdd();
Эта настройка всё равно нужна в конфигурации

2022-06-12 22:05 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Data/UserModel/UserRepository.cs
> +public static class Hashing
Для него нужен отдельный файл

2022-06-12 22:05 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Web/UserAuthenticationMiddleware.cs
> +        if (context.Request.Path.Value.ToLower() == "/user/login")
Давай избавимся от вложенности инвертировав условие внутри if и внутри вызвав return

2022-06-12 22:21 UTC, ReactiveTurtle commented on BD.sql
>  		[Likes] INT
Ты думал как ты будешь считать количество лайков?
Как ты будешь определять то, что пользователь поставил лайк?
Например для того, чтобы показать лайкнул ли он рецепт или нет

2022-06-12 22:24 UTC, ReactiveTurtle commented on src/KitchenBook.Api/Controllers/UserController.cs
> +    public IActionResult Update([FromBody] UserDto userDto)
Давай Id пользователя будем передавать в роутинге, а не в Dto

2022-06-12 22:29 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Data/UserModel/UserRepository.cs
> +        var entity = await _dbContext.User.AddAsync(user);
Здесь лучше использовать явный тип. а не var, так как непонятно что возвращает AddAsync

2022-06-12 22:30 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Web/UserAuthenticationMiddleware.cs
> +        if (context.Request.Path.Value.ToLower() == "/user/login")
И кстати по условию у тебя только при запросе "/user/login" будет проверяться пароль, а нам нужно наоборот не проверять для него

2022-06-15 10:59 UTC, Rebace commented on src/KitchenBook.Api.MessageContracts/AuthenticateModel/AuthenticateDto.cs
> +    [Required]
Required: атрибут указывает, что свойство должно быть обязательно установлено, обязательно должно иметь какое-либо значение. Если свойство имеет значение null, то оно не проходит валидацию.
Ну тип string тоже не может быть null, но мне кажется, что можно оставить для наглядности

2022-06-15 13:12 UTC, Rebace commented on src/KitchenBook.Domain/UserModel/User.cs
> +    public string? Description { get; private set; }
При создании аккаунта мы вводим только имя, логин и пароль, токен создаётся автоматически, а всё остальное пользователь потом сможет добавить в редактировании профиля, если захочет

2022-06-15 13:24 UTC, Rebace commented on BD.sql
>  		[Likes] INT
Я думаю можно создать новую базу данных, где будет храниться id пользователя и id рецепта, у которого он поставил лайк

2022-06-15 13:41 UTC, Rebace commented on src/KitchenBook.Api/Controllers/UserController.cs
> +    public IActionResult Update([FromBody] UserDto userDto)
А как это сделать? (Ведь это пост запрос и он передаёт только тело)
И зачем это делать? (Ведь у нас id всё равно не храниться на сервере)

2022-06-15 15:20 UTC, Rebace commented on src/KitchenBook.Api/Controllers/RecipeController.cs
>              var createdRecipe = await _recipeRepository.Create(new Recipe(recipeDto.Title, recipeDto.Description,
https://github.com/Rebace/KitchenBook/pull/4/commits/46515f9121f2f0245c815321e2733be423b71bec#diff-5e8f27d929f007b16607451622b95f2fd0b172b0cbbb4a564be6806b0e88a481R43

2022-06-15 15:20 UTC, Rebace commented on src/KitchenBook.Api/Controllers/UserController.cs
> +        if (Hashing.ToSHA256(loiginDto.Password) != user.Password)
https://github.com/Rebace/KitchenBook/pull/4/commits/46515f9121f2f0245c815321e2733be423b71bec#diff-a60ba44a941eba6cd73b3d1abbb9f1f0ca8433f08d79ddb588746997725d0472R28

2022-06-15 15:21 UTC, Rebace commented on src/KitchenBook.Api/Controllers/UserController.cs
> +        HttpContext.Response.Cookies.Append("Token", token);
https://github.com/Rebace/KitchenBook/pull/4/commits/46515f9121f2f0245c815321e2733be423b71bec#diff-a60ba44a941eba6cd73b3d1abbb9f1f0ca8433f08d79ddb588746997725d0472R28
https://github.com/Rebace/KitchenBook/pull/4/commits/46515f9121f2f0245c815321e2733be423b71bec#diff-24a8ede826f2ee3a008619d148c136fd04b57c5c8eba8ee6118a751bba102b47

2022-06-15 15:21 UTC, Rebace commented on src/KitchenBook.Domain/UserModel/IUserRepository.cs
> +
https://github.com/Rebace/KitchenBook/pull/4/commits/46515f9121f2f0245c815321e2733be423b71bec#diff-9c134c5ad0e36d173bb8feb61f395066eacf18f3f1477668474f9d34090b74c9L6

2022-06-15 15:23 UTC, Rebace commented on src/KitchenBook.Domain/UserModel/IUserRepository.cs
> +}
Не понимаю почему, но у меня при коммите она убирается, хотя в проекте у меня есть

2022-06-15 15:23 UTC, Rebace commented on src/KitchenBook.Infrastructure/Data/RecipeModel/Configuration/RecipeConfiguration.cs
> -            builder.Property(x => x.Id).ValueGeneratedOnAdd();
https://github.com/Rebace/KitchenBook/pull/4/commits/46515f9121f2f0245c815321e2733be423b71bec#diff-0b07070f62ae50e6b08f68909739ee1044ab0864e90f4245ea66888f5f825ca6R11
А как тогда указать, что это ключ?

2022-06-15 15:24 UTC, Rebace commented on src/KitchenBook.Infrastructure/Data/UserModel/UserRepository.cs
> +public static class Hashing
https://github.com/Rebace/KitchenBook/pull/4/commits/46515f9121f2f0245c815321e2733be423b71bec#diff-6fbfa4533eb51cfd11c42593f75c9f6b09ba458e61cf3fbfb5f238ef6a75df87

2022-06-15 15:24 UTC, Rebace commented on src/KitchenBook.Infrastructure/Web/UserAuthenticationMiddleware.cs
> +        if (context.Request.Path.Value.ToLower() == "/user/login")
https://github.com/Rebace/KitchenBook/pull/4/commits/46515f9121f2f0245c815321e2733be423b71bec#diff-2fe1f067e43f80da091f04bedb9ea96b78b2a41d1b4e093c213e95ddedef6c32R21

2022-06-15 15:24 UTC, Rebace commented on src/KitchenBook.Infrastructure/Data/UserModel/UserRepository.cs
> +        var entity = await _dbContext.User.AddAsync(user);
https://github.com/Rebace/KitchenBook/pull/4/commits/46515f9121f2f0245c815321e2733be423b71bec#diff-4680a8a1f5e732c80379d1dabd9e248c09b208c16749e1b756095ca40f03a841R28

2022-06-16 09:19 UTC, ReactiveTurtle requested changes

2022-06-16 09:19 UTC, ReactiveTurtle commented on src/KitchenBook.Api.MessageContracts/AuthenticationResponseModel/AuthenticationResponseDto.cs
> +public class AuthenticationResponseDto
Зачем тебе это Dto? Мы же логин и токен записывает записываем в Cookie

2022-06-16 09:19 UTC, ReactiveTurtle commented on src/KitchenBook.Api.MessageContracts/UserModel/UserDto.cs
> +    public string Token { get; set; }
Токен не передаем, как и Id

2022-06-16 09:19 UTC, ReactiveTurtle commented on src/KitchenBook.Api/Controllers/UserController.cs
> +[Route("user")]
Я бы назвал users, для чего:
1. Например чтобы достать авторизованного пользователя (логин в куках), ты пропишешь запрос users/authorized (или другое название вместо authorized)
2. Обновления пользователя будет происходить таким же образом
3. Не нужно будет передавать Id или Login в Dto

2022-06-16 09:19 UTC, ReactiveTurtle commented on src/KitchenBook.Api/Controllers/UserController.cs
> +        if (await _userRepository.GetByLogin(loiginDto.Login) != null)
Вынести в переменную`await _userRepository.GetByLogin(loiginDto.Login)`

2022-06-16 09:19 UTC, ReactiveTurtle commented on src/KitchenBook.Api/Controllers/UserController.cs
> +    public IActionResult Update([FromBody] UserDto userDto)
Отписал выше

2022-06-16 09:19 UTC, ReactiveTurtle commented on src/KitchenBook.Domain/AuthenticateModel/AuthenticateRequest.cs
> +    [Required]
Бесполезный атрибут, давай-ка уберём его

2022-06-16 09:19 UTC, ReactiveTurtle commented on src/KitchenBook.Domain/UserModel/IUserRepository.cs
> +}
Тогда хорошо)

2022-06-16 09:19 UTC, ReactiveTurtle commented on src/KitchenBook.Domain/UserModel/User.cs
> +    public string? Description { get; private set; }
Я понял теперь почему подчёркивается жёлтым, у тебя включена настройка на Nullable объектов
То есть, чтобы указать, что у тебя переменная nullable, тебе надо это указать с помощью "?"

2022-06-16 09:19 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Auxiliary/Hashing.cs
> +            sb.Append(bytes[i].ToString("x2"));
Что за x2?

2022-06-16 09:19 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Data/RecipeModel/Configuration/RecipeConfiguration.cs
> -            builder.Property(x => x.Id).ValueGeneratedOnAdd();
Так ведь никто тебе не мешает прописать его отдельной строчкой

2022-06-16 09:19 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Web/UserAuthenticationMiddleware.cs
> +            || context.Request.Path.Value.ToLower() == "/recipe/get-all")
Думаю можно создать список с путями для пропуска и по нему искать

2022-06-16 10:58 UTC, Rebace commented on src/KitchenBook.Infrastructure/Auxiliary/Hashing.cs
> +            sb.Append(bytes[i].ToString("x2"));
Он форматирует строку в виде двух прописных шестнадцатеричных символов.

Более подробно, аргумент "X2"является "строкой формата", которая сообщает ToString()методу, как он должен форматировать строку. В этом случае "X2" указывает, что строка должна быть отформатирована в шестнадцатеричном формате.

2022-06-16 11:18 UTC, Rebace commented on src/KitchenBook.Domain/UserModel/User.cs
> +    public string? Description { get; private set; }
Тут обязательно надо оставить Description Nullable, т.к. в приложении такое возможно, поэтому в Базе Данных оно не обязательно, а для EF его нужно указать как в БД, иначе ошибку выдаёт

2022-06-17 10:09 UTC, Rebace commented on src/KitchenBook.Infrastructure/Data/RecipeModel/Configuration/RecipeConfiguration.cs
> -            builder.Property(x => x.Id).ValueGeneratedOnAdd();
https://github.com/Rebace/KitchenBook/pull/4/commits/f0ef389244caee92522ef0960af4b57f05a2db27#diff-0b07070f62ae50e6b08f68909739ee1044ab0864e90f4245ea66888f5f825ca6R11

2022-06-17 10:13 UTC, Rebace commented on src/KitchenBook.Api.MessageContracts/AuthenticationResponseModel/AuthenticationResponseDto.cs
> +public class AuthenticationResponseDto
https://github.com/Rebace/KitchenBook/pull/4/commits/287d4d6eb63f2e9fc1ebd3826f59e5b201fc8d65#diff-fcd16dec313a373be1ebef87604c88b086c9449c43c114588fa8624c3a5fb5cf

2022-06-17 10:14 UTC, Rebace commented on src/KitchenBook.Api.MessageContracts/UserModel/UserDto.cs
> +    public string Token { get; set; }
https://github.com/Rebace/KitchenBook/pull/4/commits/287d4d6eb63f2e9fc1ebd3826f59e5b201fc8d65#diff-e7b2842b7465711a186597b2fd15b30025d83f6a23f86d495ae0e0b1d886f265L5

2022-06-17 10:14 UTC, Rebace commented on src/KitchenBook.Api/Controllers/UserController.cs
> +[Route("user")]
https://github.com/Rebace/KitchenBook/pull/4/commits/287d4d6eb63f2e9fc1ebd3826f59e5b201fc8d65#diff-a60ba44a941eba6cd73b3d1abbb9f1f0ca8433f08d79ddb588746997725d0472R10

2022-06-17 10:15 UTC, Rebace commented on src/KitchenBook.Api/Controllers/UserController.cs
> +        if (await _userRepository.GetByLogin(loiginDto.Login) != null)
https://github.com/Rebace/KitchenBook/pull/4/commits/287d4d6eb63f2e9fc1ebd3826f59e5b201fc8d65#diff-a60ba44a941eba6cd73b3d1abbb9f1f0ca8433f08d79ddb588746997725d0472R49

2022-06-17 10:15 UTC, Rebace commented on src/KitchenBook.Domain/AuthenticateModel/AuthenticateRequest.cs
> +    [Required]
https://github.com/Rebace/KitchenBook/pull/4/commits/287d4d6eb63f2e9fc1ebd3826f59e5b201fc8d65#diff-9ab2e7518afff9e325c7590142e403fb6d9bbcb86b505783c77733a3f81b0a01L7

2022-06-17 10:16 UTC, Rebace commented on src/KitchenBook.Infrastructure/Web/UserAuthenticationMiddleware.cs
> +            || context.Request.Path.Value.ToLower() == "/recipe/get-all")
https://github.com/Rebace/KitchenBook/pull/4/commits/287d4d6eb63f2e9fc1ebd3826f59e5b201fc8d65#diff-2fe1f067e43f80da091f04bedb9ea96b78b2a41d1b4e093c213e95ddedef6c32R21

2022-06-17 10:21 UTC, Rebace commented on src/KitchenBook.Api/Controllers/UserController.cs
> +    public IActionResult Update([FromBody] UserDto userDto)
https://github.com/Rebace/KitchenBook/pull/4/commits/287d4d6eb63f2e9fc1ebd3826f59e5b201fc8d65#diff-a60ba44a941eba6cd73b3d1abbb9f1f0ca8433f08d79ddb588746997725d0472R70

2022-06-20 08:22 UTC, ReactiveTurtle commented on src/KitchenBook.Domain/UserModel/User.cs
> +    public string? Description { get; private set; }
Изначально string в C# это ссылочный тип и поэтому он может быть null, ты скорее всего включил настройку для того, чтобы для string нужно было указывать Nullable
Вообще там не нужно ставить этот знак вопроса в C# по умолчанию для EF, но видимо из-за этой настройки тебе это нужно

2022-06-20 08:29 UTC, ReactiveTurtle requested changes

2022-06-20 08:29 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Auxiliary/AppendToken.cs
> +public static class AddingToCookies
Почему AddingToCookies, я думаю стоит назвать HttpResponseCookieExtensions
Так же и с файлом

2022-06-20 08:29 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Auxiliary/AppendToken.cs
> +    public static void AppendTokenToCookies(this HttpResponse HttpContext, string token)
Тип HttpResponse, а название HttpContext, аргументы пишем с маленькой буквы и название переменной должно отражать его смысл
В данном случае стоит его назвать просто по названию типа

2022-06-20 08:29 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Auxiliary/Hashing.cs
> +            sb.Append(bytes[i].ToString("x2"));
Понял)

2022-06-20 08:30 UTC, ReactiveTurtle commented
https://github.com/Rebace/KitchenBook/pull/4/files#diff-d4b743c5e0632450da7f172cc8be5d0a4dc96b8496bf5fb00439b25f4a818d1a
Удали файл

2022-06-20 08:34 UTC, ReactiveTurtle commented on src/KitchenBook.Infrastructure/Web/UserAuthenticationMiddleware.cs
> +            "/users/update" // Для проверки
Коммент не даёт никакой информации читателю, понятно, что ты поймешь, ты в контексте, но у человека который откроет этот файл возникнут вопросы и ему придётся разбираться в коде
Лучше подобрать новое название для переменной
Например: skippedRoutes или skippedRouteList
Можешь поискать вместо skipped более подходящее слово)

2022-06-28 10:07 UTC, merged